version: "1.0"
services:
  hamburger-company:
    build: .
    restart: on-failure
    container_name: hamburger-company-container
    ports:
      - 8080:8080
    depends_on:
      - hamburger-mysql_db
    links:
      - hamburger-mysql_db:app_db
  hamburger-mysql_db:
    image: "mysql"
    restart: on-failure
    container_name: mysql-container
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: thcompany_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin