server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thcompany_db
    username: root
    password: rgit@1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false