server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      client-id: orderProducer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5
      batch-size: 16384
      buffer-memory: 33554432
      linger-ms: 1
      enable-Idempotence: true
      transactionalId: orderTransaction
    consumer:
      bootstrap-servers: localhost:9092
      client-id: orderConsumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      isolationLevel: read_committed
      max-poll-records: 7
      heartbeat-interval: 6000

kafka:
  topic:
    name:
      california: california
      newyork: newyork
      texas: texas
      illinois: illinois
      other: other
      groupId: states



