server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_db
    username: root
    password: rgit@1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false